apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: springboot-k8s
  labels:
    app: mysql
spec:
  replicas: 1
  template:
    metadata:
      name: mysql
      labels:
        app: mysql
    spec:
#      imagePullSecrets:
#        - name: docker-registry
      containers:
        - name: mysql
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: mysql
            - name: MYSQL_DATABASE
              value: inventory-service
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - mountPath: /var/lob/mysql
              name: mysql-persistent-storage
      restartPolicy: Always
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
  selector:
    matchLabels:
      app: mysql

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
  namespace: springboot-k8s
spec:
  selector:
    app: mysql
    tier: database
  ports:
    - port: 80
      targetPort: 3306
  clusterIP: None

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: springboot-k8s
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

