apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-app
  namespace: springboot-k8s
  labels:
    app: order-service-app
spec:
  replicas: 1
  template:
    metadata:
      name: order-service-app
      labels:
        app: order-service-app
    spec:
      containers:
        - name: order-service-app
          image: sitankasala/order-service:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
      restartPolicy: Always
  selector:
    matchLabels:
      app: order-service-app
