apiVersion: v1
kind: Service
metadata:
  name: eureka
  labels:
    app: eureka
  namespace: springboot-k8s
spec:
  clusterIP: None
  selector:
    app: eureka
  ports:
    - port: 80
      targetPort: 8761
      name: eureka
---

apiVersion: v1
kind: Service
metadata:
  name: eureka-lb
  namespace: springboot-k8s
  labels:
    app: eureka
spec:
  selector:
    app: eureka
  ports:
    - port: 8080
      targetPort: 8761
  type: NodePort