apiVersion: v1
kind: Service
metadata:
  name: inventory-service-svc
  namespace: springboot-k8s
spec:
  selector:
    app: inventory-service-app
  ports:
    - port: 80
      targetPort: 8082
  type: NodePort