apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
  namespace: springboot-k8s
spec:
  selector:
    app: mysql
    tier: database
  ports:
    - port: 80
      targetPort: 3306
  clusterIP: None